---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-mesh-operator
  namespace: open-cluster-management
  labels:
    app: multicluster-mesh-operator
spec:
  selector:
    matchLabels:
      app: multicluster-mesh-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: multicluster-mesh-operator
      labels:
        app: multicluster-mesh-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /multicluster-mesh-operator
        args:
        - --leader-elect
        image: quay.io/morvencao/multicluster-mesh-operator:latest
        name: multicluster-mesh-operator
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /usr/local/bin/prestop.sh
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: multicluster-mesh-operator
      terminationGracePeriodSeconds: 10
