# permissions for end users to view globalmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalmesh-viewer-role
rules:
- apiGroups:
  - mesh.open-cluster-management.io
  resources:
  - globalmeshes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mesh.open-cluster-management.io
  resources:
  - globalmeshes/status
  verbs:
  - get
