# permissions for end users to edit meshdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshdeployment-editor-role
rules:
- apiGroups:
  - mesh.open-cluster-management.io
  resources:
  - meshdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.open-cluster-management.io
  resources:
  - meshdeployments/status
  verbs:
  - get
