# permissions for end users to view meshdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshdeployment-viewer-role
rules:
- apiGroups:
  - mesh.open-cluster-management.io
  resources:
  - meshdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mesh.open-cluster-management.io
  resources:
  - meshdeployments/status
  verbs:
  - get
