# permissions for end users to edit meshfederations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshfederation-editor-role
rules:
- apiGroups:
  - mesh.open-cluster-management.io
  resources:
  - meshfederations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.open-cluster-management.io
  resources:
  - meshfederations/status
  verbs:
  - get
