apiVersion: mesh.open-cluster-management.io/v1alpha1
kind: MeshFederation
metadata:
  name: meshfederation-sample
spec:
  meshPeers:
  - peers:
    - managedcluster1-mesh
    - managedcluster1-mesh
  trustConfig:
    trustType: Limited
