apiVersion: mesh.open-cluster-management.io/v1alpha1
kind: MeshDeployment
metadata:
  name: meshdeployment-sample
spec:
  clusters:
  - managedcluster1
  - managedcluster2
  controlPlane:
    components:
    - grafana
    - istio-discovery
    - istio-egress
    - istio-ingress
    - kiali
    - mesh-config
    - telemetry-common
    - tracing
    namespace: mesh-system
    profiles:
    - default
    version: v2.1
  meshMemberRoll:
  - mesh-apps
  meshProvider: Openshift Service Mesh
  trustDomain: mesh.local
